<?php
$this->headTitle('Update user information');
$com = $this->Communicator();

?>
<div class="row">          
    <div class="col-xs-12">
        <h2><?php echo $this->translate('Update user password')?></h2>
        <div class="col-xs-4">
            <form class="form-horizontal" method="post" action="">
          
                <div id="alert"><?php $com->printMessage() ?></div>

                <div class="form-group <?php $com->printErrorClass('password'); ?>">
                    <label><?php echo $this->translate('Password')?>*</label>
                    <input type="password" id="password" name="password" required="required" class="form-control">
                    <?php $com->printFieldErrors('password'); ?>
                </div>

                <div class="form-group" id="submit" style="margin-top:10px">
                    <input type="submit" id="submit" value="<?php echo $this->translate('Save')?>" class="btn btn-primary">
                </div>

            </form>
        </div>
   </div>
</div>
