<?php

$this->headTitle('Add domains to the blacklist');

$com = $this->Communicator();

?>
<div class="row">          
    <div class="col-xs-12">
        <form class="form-horizontal" method="post" action="">
      
            <div><?php $com->printMessage() ?></div>

            <div class="form-group <?php $com->printErrorClass('domain'); ?>">
                <label><?php echo $this->translate('Domain name')?>*</label>
                <input type="text" id="domain" name="domain" value="<?php echo $this->escapeHtml($this->domain) ?>" required="required" class="form-control">
                <?php $com->printFieldErrors('domain'); ?>
            </div>

            <div class="form-group" id="submit" style="margin-top:10px">
                <button class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $this->translate('Save')?></button>
            </div>

        </form>
   </div>
</div>