<?php
$com = $this->Communicator();
$userId = $this->GlobalVars('identity.id', 0);
?>

<div class="row">
    <div class="col-lg-4">
        <ul>
            <li><a href="<?php echo $this->url('backend', array('controller' => 'sql', 'action' => 'index')); ?>">SQL</a></li>
            <!--li><a href="<?php echo $this->url('backend', array('controller' => 'instance', 'action' => 'approval-pending')); ?>">Approval pending</a></li-->
            <li><a href="<?php echo $this->url('backend', array('controller' => 'instance', 'action' => 'list')); ?>">Instances</a></li>
            <li><a href="<?php echo $this->url('backend', array('controller' => 'instance', 'action' => 'add-instance')); ?>">Add Instance</a></li>
            <li><a href="<?php echo $this->url('backend', array('controller' => 'BlacklistDomain', 'action' => 'list')); ?>">Blacklist Domain</a></li>
            <li>
                <a class="dump-database btn btn-default btn-xs" class="btn btn-default btn-xs" target="_blank" href="">Dump master database</a>
                <select id="instance_lang">
                    <option value="">Please choose a value</option>
                    <option value="en">trial.paradisolms.com</option>
                    <option value="es">master.es.paradisolms.net</option>
                </select>
            </li>
        </ul>
    </div>
</div>

<script>
jQuery(function(){
    $(".dump-database").click(function(e){
        var lang = $("#instance_lang").val()
        if(lang == "")
        {
            alert("Please choose an instance from the dropdown");
            e.preventDefault();
        }

        var url = "<?php echo $this->url('backend', array('controller' => 'sql', 'action' => 'dump-database')); ?>";
        url += "/lang/" + lang;

        $(this).attr("href", url);
    });
});

</script>
