<?php
$com = $this->Communicator();
$userId = $this->GlobalVars('identity.id', 0);
?>

<div class="row">
    <div class="col-lg-4">
        <ul>
            <li><a href="<?php echo $this->url('backend', array('controller' => 'sql', 'action' => 'index')); ?>">SQL</a></li>
            <!--li><a href="<?php echo $this->url('backend', array('controller' => 'instance', 'action' => 'approval-pending')); ?>">Approval pending</a></li-->
            <li><a href="<?php echo $this->url('backend', array('controller' => 'instance', 'action' => 'list')); ?>">Instances</a></li>
            <li><a href="<?php echo $this->url('backend', array('controller' => 'instance', 'action' => 'add-instance')); ?>">Add Instance</a></li>
            <li><a href="<?php echo $this->url('backend', array('controller' => 'BlacklistDomain', 'action' => 'list')); ?>">Blacklist Domain</a></li>
            <li><a href="<?php echo $this->url('backend', array('controller' => 'blacklist-phrase', 'action' => 'list')); ?>">Blacklist Phrase</a></li>
            <li>
                <select class="dump_instance">
                    <option value="">Dump database</option>
                    <option value="en">trial.paradisolms.com</option>
                    <option value="es">master.es.paradisolms.net</option>
                </select>
            </li>
        </ul>
    </div>
</div>