<?php
$com = $this->Communicator();

$valueOptions = array(
    'en' => 'English'
    ,'es' => 'Español'
);
?>
<div class="row">          
    <div class="col-xs-12">
        <h2><?php echo $this->translate('Create Account')?></h2>
        <div class="col-xs-4">
            <form class="form-horizontal" method="post" action="<?php echo $this->url($this->route_name, array('controller' => 'instance', 'action' => 'add-instance')) ?>">
          
                <div id="alert"><?php $com->printMessage() ?></div>

                <div class="form-group <?php $com->printErrorClass('email'); ?>">
                    <label><?php echo $this->translate('Email address')?>*</label>
                    <input type="email" id="email" name="email" value="<?php echo $this->escapeHtml($this->email) ?>" required="required" class="form-control">
                    <?php $com->printFieldErrors('email'); ?>
                </div>

                <div class="form-group <?php $com->printErrorClass('first_name'); ?>">
                    <label><?php echo $this->translate('First name')?>*</label>
                    <input type="text" id="firstname" name="first_name" value="<?php echo $this->escapeHtml($this->first_name) ?>" required="required" class="form-control">
                    <?php $com->printFieldErrors('first_name'); ?>
                </div>

                <div class="form-group <?php $com->printErrorClass('last_name'); ?>">
                    <label><?php echo $this->translate('Last name')?>*</label>
                    <input type="text" id="lastname" name="last_name" value="<?php echo $this->escapeHtml($this->last_name) ?>" required="required" class="form-control">
                    <?php $com->printFieldErrors('last_name'); ?>
                </div>

                <div class="form-group required large <?php $com->printErrorClass('lang'); ?>" required="required">
                    <label><?php echo $this->translate('Language')?>*</label>
                    
                    
                    <?php echo $this->HtmlSelect('lang', $valueOptions, $this->lang, null, array('class' =>  'form-control'))?>
                    <?php $com->printFieldErrors('lang'); ?>
                </div>
                 
                <div class="form-group" id="submit" style="margin-top:10px">
                    <input type="submit" id="submit" value="<?php echo $this->translate('Create account')?>" class="btn btn-primary">
                </div>

            </form>
        </div>
   </div>
</div>
